In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [5]:
df = pd.read_csv("data/Aviation_Data.csv")

/Users/samalainabayeva/anaconda3/envs/learn-env/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3145: DtypeWarning: Columns (6,7,28) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [68]:
pd.options.display.max_columns = 50

In [24]:
df.shape

(90348, 31)

In [25]:
df_clean.shape

(88889, 31)

In [89]:
df.describe()

,Number.of.Engines,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured
count,82805.000000,77488.000000,76379.000000,76956.000000,82977.000000
mean,1.146585,0.647855,0.279881,0.357061,5.325440
std,0.446510,5.485960,1.544084,2.235625,27.913634
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,1.000000
75%,1.000000,0.000000,0.000000,0.000000,2.000000
max,8.000000,349.000000,161.000000,380.000000,699.000000

In [23]:
df.isna().sum()

Event.Id                   1459
Investigation.Type            0
Accident.Number            1459
Event.Date                 1459
Location                   1511
Country                    1685
Latitude                  55966
Longitude                 55975
Airport.Code              40099
Airport.Name              37558
Injury.Severity            2459
Aircraft.damage            4653
Aircraft.Category         58061
Registration.Number        2776
Make                       1522
Model                      1551
Amateur.Built              1561
Number.of.Engines          7543
Engine.Type                8536
FAR.Description           58325
Schedule                  77766
Purpose.of.flight          7651
Air.carrier               73700
Total.Fatal.Injuries      12860
Total.Serious.Injuries    13969
Total.Minor.Injuries      13392
Total.Uninjured            7371
Weather.Condition          5951
Broad.phase.of.flight     28624
Report.Status              7840
Publication.Date          16689
dtype: int64

In [10]:
df_clean = df.loc[(df["Investigation.Type"] == "Accident") | (df["Investigation.Type"] == "Incident")]
df_clean.isna().sum()

Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                     52
Country                     226
Latitude                  54507
Longitude                 54516
Airport.Code              38640
Airport.Name              36099
Injury.Severity            1000
Aircraft.damage            3194
Aircraft.Category         56602
Registration.Number        1317
Make                         63
Model                        92
Amateur.Built               102
Number.of.Engines          6084
Engine.Type                7077
FAR.Description           56866
Schedule                  76307
Purpose.of.flight          6192
Air.carrier               72241
Total.Fatal.Injuries      11401
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Uninjured            5912
Weather.Condition          4492
Broad.phase.of.flight     27165
Report.Status              6381
Publication.Date          15230
dtype: int64

In [9]:
df_clean.isna().sum()

Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                     52
Country                     226
Latitude                  54507
Longitude                 54516
Airport.Code              38640
Airport.Name              36099
Injury.Severity            1000
Aircraft.damage            3194
Aircraft.Category         56602
Registration.Number        1317
Make                         63
Model                        92
Amateur.Built               102
Number.of.Engines          6084
Engine.Type                7077
FAR.Description           56866
Schedule                  76307
Purpose.of.flight          6192
Air.carrier               72241
Total.Fatal.Injuries      11401
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Uninjured            5912
Weather.Condition          4492
Broad.phase.of.flight     27165
Report.Status              6381
Publication.Date          15230
dtype: int64

In [13]:
df_drop = df_clean.drop(columns=["Latitude", "Longitude"])
df_drop.isna().sum()

Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                     52
Country                     226
Airport.Code              38640
Airport.Name              36099
Injury.Severity            1000
Aircraft.damage            3194
Aircraft.Category         56602
Registration.Number        1317
Make                         63
Model                        92
Amateur.Built               102
Number.of.Engines          6084
Engine.Type                7077
FAR.Description           56866
Schedule                  76307
Purpose.of.flight          6192
Air.carrier               72241
Total.Fatal.Injuries      11401
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Uninjured            5912
Weather.Condition          4492
Broad.phase.of.flight     27165
Report.Status              6381
Publication.Date          15230
dtype: int64

In [17]:
df["Latitude"].notnull().sum()

34382

In [22]:
df["Latitude"].describe()

count       34382
unique      25592
top       332739N
freq           19
Name: Latitude, dtype: object

In [18]:
df["Longitude"].notnull().sum()

34373

In [21]:
df["Longitude"].describe()

count        34373
unique       27156
top       0112457W
freq            24
Name: Longitude, dtype: object

In [26]:
df_clean.isna().sum()

Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                     52
Country                     226
Latitude                  54507
Longitude                 54516
Airport.Code              38640
Airport.Name              36099
Injury.Severity            1000
Aircraft.damage            3194
Aircraft.Category         56602
Registration.Number        1317
Make                         63
Model                        92
Amateur.Built               102
Number.of.Engines          6084
Engine.Type                7077
FAR.Description           56866
Schedule                  76307
Purpose.of.flight          6192
Air.carrier               72241
Total.Fatal.Injuries      11401
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Uninjured            5912
Weather.Condition          4492
Broad.phase.of.flight     27165
Report.Status              6381
Publication.Date          15230
dtype: int64

In [30]:
df_clean[df_clean["Location"].isna()]

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
4239,20001214X42513,Accident,LAX83LAMS4,1983-03-29,NaN,United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,0.0,0.0,0.0,VMC,Unknown,Probable Cause,NaN
5726,20001214X44103,Accident,DCA83RA001,1983-08-04,NaN,Pakistan,NaN,NaN,NaN,NaN,...,Unknown,NaN,0.0,0.0,0.0,245.0,UNK,NaN,Foreign,06-02-1995
7948,20001214X39337,Incident,MIA84IA140,1984-04-14,NaN,Martinique,NaN,NaN,NaN,NaN,...,Unknown,Pan American (paaa),0.0,0.0,0.0,263.0,VMC,Climb,Probable Cause,NaN
10546,20001214X41859,Accident,MIA85LAMS1,1984-12-23,NaN,United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,0.0,0.0,0.0,IMC,Unknown,Probable Cause,NaN
12527,20001214X37399,Accident,CHI85FAMS3,1985-08-03,NaN,United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,NaN
22058,20001213X27404,Accident,DCA89WA019,1988-12-16,NaN,Hong Kong,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,15.0,UNK,NaN,Foreign,06-02-1995
24214,20001213X29712,Accident,SEA90FAMS1,1989-10-06,NaN,United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,0.0,0.0,0.0,VMC,Unknown,Probable Cause,26-06-1992
26295,20001212X24088,Accident,MIA90WA175,1990-08-07,NaN,Anguilla,NaN,NaN,NaN,NaN,...,Unknown,NaN,0.0,0.0,0.0,1.0,VMC,NaN,Foreign,06-02-1995
26881,20001212X24491,Accident,LAX91LA013,1990-10-22,NaN,American Samoa,NaN,NaN,NaN,NaN,...,Aerial Observation,NaN,2.0,0.0,0.0,0.0,VMC,Maneuvering,Probable Cause,30-12-1992
27261,20001212X16361,Accident,MIA91WA066,1991-01-14,NaN,Montserrat,NaN,NaN,NaN,NaN,...,Business,NaN,1.0,0.0,0.0,0.0,VMC,NaN,Foreign,05-08-1996
29763,20001211X14040,Accident,MIA92WA066,1992-01-23,NaN,Dominica,NaN,NaN,NaN,NaN,...,Instructional,NaN,2.0,0.0,0.0,0.0,VMC,NaN,Foreign,05-08-1996
32633,20001211X12184,Accident,LAX93LA209,1993-04-28,NaN,American Samoa,NaN,NaN,NaN,NaN,...,Aerial Observation,NaN,0.0,0.0,0.0,2.0,VMC,Landing,Probable Cause,30-06-1994
34372,20001206X00600,Accident,BFO94WA031,1994-01-13,NaN,France,NaN,NaN,NaN,NaN,...,Ferry,NaN,0.0,0.0,1.0,0.0,VMC,NaN,Foreign,04-03-1994
36222,20001206X02391,Accident,BFO95WA004,1994-10-13,NaN,Switzerland,NaN,NaN,NaN,NaN,...,Unknown,NaN,0.0,0.0,0.0,0.0,UNK,NaN,Foreign,23-11-1994
38569,20001207X04783,Accident,NYC96WA018,1995-10-24,NaN,NaN,NaN,NaN,NaN,NaN,...,Positioning,NaN,1.0,0.0,0.0,0.0,UNK,NaN,Foreign,01-12-1995
39070,20001208X05317,Accident,NYC96WA070,1996-02-15,NaN,Zambia,NaN,NaN,NaN,NaN,...,Unknown,NaN,5.0,0.0,0.0,0.0,UNK,NaN,Foreign,09-04-1996
39241,20001208X05477,Accident,NYC96WA076,1996-03-17,NaN,Iceland,NaN,NaN,NaN,NaN,...,Unknown,NaN,0.0,0.0,1.0,0.0,UNK,NaN,Foreign,19-03-1996
40220,20001208X06569,Accident,LAX96WA348,1996-08-01,NaN,Fiji,NaN,NaN,NaN,NaN,...,Ferry,NaN,0.0,0.0,0.0,1.0,VMC,NaN,Foreign,07-04-1998
41677,20001208X07698,Accident,DCA97WA044,1997-04-30,NaN,Cambodia,NaN,NaN,NaN,NaN,...,Unknown,NaN,2.0,NaN,NaN,NaN,UNK,NaN,Foreign,NaN
42630,20001208X08827,Accident,DCA97RA063,1997-09-06,NaN,Saudi Arabia,NaN,NaN,NaN,NaN,...,Unknown,NaN,0.0,0.0,0.0,0.0,UNK,NaN,Foreign,27-01-1998
42746,20001208X08920,Accident,NYC97WA191,1997-09-24,NaN,Belgium,NaN,NaN,NaN,NaN,...,Unknown,NaN,2.0,0.0,0.0,0.0,UNK,NaN,Foreign,05-01-1998
43184,20001208X09293,Accident,DCA98RA013,1997-12-19,NaN,Indonesia,NaN,NaN,NaN,NaN,...,Unknown,NaN,97.0,0.0,0.0,0.0,UNK,NaN,Foreign,27-01-1998
43267,20001211X09475,Accident,LAX98WA073,1998-01-09,NaN,Philippines,NaN,NaN,NaN,NaN,...,Ferry,NaN,0.0,0.0,0.0,2.0,VMC,NaN,Foreign,21-01-1998
43401,20001211X09535,Accident,DCA98WA044,1998-02-16,NaN,Taiwan,NaN,NaN,NaN,NaN,...,Unknown,NaN,0.0,0.0,0.0,0.0,UNK,NaN,Foreign,27-08-1998
43491,20001211X09654,Incident,DCA98WA037,1998-03-06,NaN,Bahrain,NaN,NaN,NaN,NaN,...,Unknown,NaN,0.0,0.0,0.0,4.0,UNK,NaN,Foreign,27-08-1998
43702,20001211X09840,Incident,DCA98WA072,1998-04-14,NaN,France,NaN,NaN,NaN,NaN,...,Unknown,NaN,0.0,0.0,0.0,0.0,UNK,NaN,Foreign,29-07-1998
44232,20001211X10284,Accident,DCA98WA058,1998-06-26,NaN,Cote D'ivoire,NaN,NaN,NaN,NaN,...,Unknown,NaN,7.0,0.0,0.0,0.0,UNK,NaN,Foreign,20-08-1998
44244,20001211X10285,Accident,DCA98WA060,1998-06-27,NaN,Netherlands,NaN,NaN,NaN,NaN,...,Unknown,NaN,NaN,NaN,2.0,1.0,UNK,NaN,Foreign,NaN
44272,20001211X10286,Accident,DCA98WA061,1998-06-30,NaN,Nigeria,NaN,NaN,NaN,NaN,...,Unknown,NaN,5.0,4.0,NaN,NaN,UNK,NaN,Foreign,NaN
44710,20001211X10885,Accident,IAD98WA101,1998-08-17,NaN,Jamaica,NaN,NaN,NaN,NaN,...,Instructional,NaN,2.0,0.0,0.0,0.0,UNK,NaN,Foreign,27-08-1998
44873,20001211X11042,Incident,DCA99WA003,1998-09-12,NaN,Vietnam,NaN,NaN,NaN,NaN,...,Unknown,NaN,NaN,NaN,NaN,200.0,VMC,NaN,Foreign,NaN
44995,20001211X11162,Accident,NYC98WA194,1998-09-28,NaN,Iceland,NaN,NaN,NaN,NaN,...,Ferry,NaN,0.0,0.0,0.0,1.0,VMC,NaN,Foreign,05-10-1998
45311,20001211X11407,Incident,DCA99WA013,1998-11-27,NaN,Singapore,NaN,NaN,NaN,NaN,...,Unknown,NaN,0.0,0.0,0.0,0.0,UNK,NaN,Foreign,16-12-1998
45924,20001205X00448,Accident,DCA99RA057,1999-04-14,NaN,Finland,NaN,NaN,NaN,NaN,...,Unknown,NaN,0.0,0.0,0.0,2.0,UNK,NaN,Foreign,20-04-1999
46281,20001212X19014,Accident,IAD99WA072,1999-06-05,NaN,France,NaN,NaN,NaN,NaN,...,Instructional,NaN,NaN,NaN,NaN,2.0,UNK,NaN,Foreign,NaN
46717,20001212X19232,Accident,DCA99WA070,1999-07-29,NaN,Fiji,NaN,NaN,NaN,NaN,...,Unknown,NaN,NaN,NaN,NaN,18.0,UNK,NaN,Foreign,NaN
47929,20001212X20730,Accident,NYC00WA090,2000-03-02,NaN,Botswana,NaN,NaN,NaN,NaN,...,Unknown,NaN,0.0,5.0,0.0,0.0,UNK,NaN,Foreign,20-03-2000
48351,20010324X00649,Incident,DCA00WA048,2000-05-11,NaN,Norway,NaN,NaN,NaN,NaN,...,Unknown,NaN,NaN,NaN,NaN,NaN,UNK,NaN,Foreign,NaN
49183,20001212X21854,Accident,NYC00RA249,2000-08-23,NaN,Denmark,NaN,NaN,NaN,NaN,...,Unknown,NaN,2.0,0.0,0.0,0.0,UNK,NaN,Foreign,10-10-2000
50016,20010323X00639,Incident,DCA01WA019,2001-01-30,NaN,Australia,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Foreign,NaN
52628,20020606X00818,Accident,ATL02WA109,2002-05-23,NaN,United States,19.6,-81.683333,NaN,NaN,...,Personal,NaN,1.0,NaN,NaN,NaN,VMC,NaN,Foreign,06-06-2002
53640,20080325X00377,Incident,ENG02WA014,2002-10-11,NaN,Australia,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Foreign,25-03-2008
54050,20030127X00112,Accident,SEA03LA029,2003-01-15,NaN,United States,30.416667,-147.416667,NaN,NaN,...,Personal,NaN,NaN,1.0,NaN,5.0,VMC,Cruise,Probable Cause,25-11-2003
55513,20030917X01553,Accident,MIA03LA182,2003-09-14,NaN,United States,27.093333,-79.886666,NaN,NaN,...,Personal,NaN,1.0,NaN,NaN,NaN,VMC,Maneuvering,Probable Cause,29-09-2004
56394,20040422X00501,Accident,DCA04MA030,2004-03-23,NaN,United States,NaN,NaN,GLS,Galveston - Shoals,...,NaN,"Era Aviation, Inc.",10.0,NaN,NaN,NaN,VMC,Cruise,Probable Cause,22-08-2006
57693,20041102X01734,Incident,DCA05WA001,2004-10-19,NaN,Argentina,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,12.0,NaN,NaN,Foreign,02-11-2004
57695,20041028X01714,Accident,CHI05MA011,2004-10-20,NaN,United States,42.075556,-86.867223,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,5.0,VMC,Climb,Probable Cause,29-11-2007
59073,20050719X01053,Accident,DFW05LA180,2005-07-11,NaN,United States,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3.0,VMC,Landing,Probable Cause,28-02-2006
59665,20051018X01683,Accident,DFW06FAMS1,2005-10-06,NaN,United States,NaN,NaN,LFT,Lafayette Regional Airport,...,NaN,Industrial Helicopters Inc. (dba: Industrial H...,3.0,NaN,NaN,NaN,VMC,Unknown,Probable Cause,28-12-2006
61431,20060922X01377,Incident,DCA06WA074,2006-09-17,NaN,Iceland,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Foreign,22-09-2006
62438,20070518X00583,Incident,DCA07WA044,2007-04-29,NaN,Brazil,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Foreign,18-05-2007
63709,20121004X53806,Incident,ERA13IA006,2007-11-09,NaN,Unknown,46.573056,-37.768334,NaN,NaN,...,Public Aircraft - Federal,NaN,NaN,NaN,NaN,6.0,IMC,Maneuvering,Probable Cause,30-05-2013

In [45]:
other_Report_Status = df_clean[df_clean["Report.Status"] != "Probable Cause"]

### 61754 entries where the report was filed for probable cause!

In [46]:
other_Report_Status["Report.Status"].unique()

array(['Factual', 'Foreign', 'Preliminary', ...,
       'The pilot did not ensure adequate clearance from construction vehicles during taxi.',
       'The pilot\x92s failure to secure the magneto switch before attempting to hand rotate the engine which resulted in an inadvertent engine start, a runaway airplane, and subsequent impact with parked airplanes. Contributing to the accident was the failure to properly secure the airplane with chocks.',
       'The pilot\x92s loss of control due to a wind gust during landing.'],
      dtype=object)

### SMALL AIRCRAFT/PILOT ERROR, can PROBABLY BE DROPPED AND SEPARATED FOR ANALYSIS!!!!

In [50]:
long_form = df_clean[df_clean["Report.Status"].notnull()]

In [63]:
pilot_error_reports = long_form.loc[long_form["Report.Status"].str.contains("pilot")]["Report.Status"]

In [64]:
pilot_error = long_form.loc[long_form["Report.Status"].str.contains("pilot")]

In [69]:
pilot_error.head()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,Injury.Severity,Aircraft.damage,Aircraft.Category,Registration.Number,Make,Model,Amateur.Built,Number.of.Engines,Engine.Type,FAR.Description,Schedule,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
63913,20080107X00026,Accident,SEA08LA057,2008-01-01,"Sonoma, CA",United States,381326N,1222659W,OQ3,Schellville/Sonoma,Non-Fatal,Substantial,Airplane,N15EX,Barnard/Stancil,Glastar,Yes,1.0,Reciprocating,091,NaN,Personal,Kenneth Couey,0.0,0.0,0.0,3.0,VMC,NaN,The departing pilot's inadequate visual lookout.,25-09-2020
63914,20080109X00036,Accident,DFW08CA054,2008-01-01,"Arcola, TX",United States,293022N,0952836W,AXH,HOUSTON-SOUTHWEST,Non-Fatal,Substantial,Airplane,N579RM,Micco Aircraft Company,MAC-145B,No,1.0,Reciprocating,091,NaN,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,The pilot's failure to maintain directional co...,25-09-2020
63915,20080115X00051,Accident,DEN08CA047,2008-01-02,"Loveland, CO",United States,040276N,0010504W,FNL,Fort Collins Loveland,Non-Fatal,Substantial,Airplane,N24965,Cessna,152,No,1.0,Reciprocating,091,NaN,Instructional,Colorado Contrails,0.0,0.0,0.0,1.0,VMC,NaN,the student pilot's premature flare resulting ...,25-09-2020
63916,20080210X00166,Accident,NYC08CA074,2008-01-02,"Brunswick, GA",United States,003196N,0812328W,SSI,Malcolm McKinnon Airport,Non-Fatal,Substantial,Airplane,N724BB,Beech,A36,No,1.0,Reciprocating,091,NaN,Business,BK Corporation,0.0,0.0,0.0,3.0,VMC,NaN,The pilot's inadequate compensation for wind c...,25-09-2020
63921,20080115X00047,Accident,MIA08LA035,2008-01-05,"Spotsylvania, VA",United States,038128N,0773515W,NaN,NaN,Non-Fatal,Substantial,Airplane,N758FQ,Cessna,R172K,No,1.0,Reciprocating,091,NaN,Personal,Neil T. Wallace,0.0,1.0,0.0,0.0,VMC,NaN,The pilot's failure to follow the checklist an...,25-09-2020

In [73]:
pilot_error["Make"] = pilot_error["Make"].str.upper()

<ipython-input-73-7b93352e6355>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pilot_error["Make"] = pilot_error["Make"].str.upper()

### The overwhelming majority of pilot errors are in small aircraft

### Top 5 represent 50% of pilot errors, all small planes, Bell no longer made, was WWII plane

In [91]:
pilot_error["Make"].value_counts(normalize=False)[:10]

CESSNA                 3638
PIPER                  2056
BEECH                   667
BELL                    272
MOONEY                  181
AIR TRACTOR INC         145
ROBINSON HELICOPTER     142
MAULE                   128
BELLANCA                125
AERONCA                 125
Name: Make, dtype: int64

In [67]:
pilot_error["Weather.Condition"].value_counts(normalize=True)

VMC    0.946893
IMC    0.050048
Unk    0.003058
Name: Weather.Condition, dtype: float64

In [ ]:
pilot_error[]

In [61]:
for i in pilot_error[:5]:
    print(i, '\n')

The departing pilot's inadequate visual lookout.

The pilot's failure to maintain directional control.  A contributing factor was the prevailing crosswind.

the student pilot's premature flare resulting in the loss of aircraft control.

The pilot's inadequate compensation for wind conditions.  A factor in the accident was the wind gust.

The pilot's failure to follow the checklist and failure to achieve the proper touchdown point during a forced landing. Contributing to the accident was a loss of engine power due to a cracked No. 4 top sparkplug insulator, resulting in pre-ignition/detonation and the failure of the No. 2 connecting rod cap due to evacuation of the oil supply.